<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
<p>
<ul>
    <li>${myList[0].name}</li>
    <li>${myList[0].address}</li>
    <li>${myList[0].age}</li>
</ul>
</p><p>
<ul>
    <li>${myList[1].name}</li>
    <li>${myList[1].address}</li>
    <li>${myList[1].age}</li>
</ul>
</p><p>
<ul>
    <li>${myList[2].name}</li>
    <li>${myList[2].address}</li>
    <li>${myList[2].age}</li>
</ul>
</p>
</body>
</html>
