<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
<ul>
    <li>${cars[0].modelName}</li>
    <li>${cars[0].price}</li>
    <li>${cars[0].color}</li>
</ul>
<ul>
    <li>${cars[1].modelName}</li>
    <li>${cars[1].price}</li>
    <li>${cars[1].color}</li>
</ul>
<ul>
    <li>${cars[2].modelName}</li>
    <li>${cars[2].price}</li>
    <li>${cars[2].color}</li>
</ul>
</body>
</html>
